name: libroteca
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  mysql1: ^0.20.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.5.3
  flutter_native_splash: ^2.0.4+1

flutter_native_splash:
  image: assets/images/libroteca.png
  color: "#fff0d2"
  android: true
  ios: true
  web: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
