name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

    
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.4.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Verificar el formato
      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      # Analizar el proyecto
      - name: Analyze project source
        run: flutter analyze

      # Ejecutar pruebas
      - name: Run tests
        run: flutter test
